### ISSUE TITLE
Combine @dataclass and @dataslots into one decorator?

### ISSUE THREAD

**Issue by TylerYep** [starhel/dataslots#14]
Hi, would it be possible to combine @dataclass and @dataslots into one decorator? It seems redundant in a lot of cases to have two stacked decorators, and having to add the extra import `from dataclasses import dataclass` line in these files.

Thanks!

**Comment by starhel** [comment]
That's probably should be something like
```
def dataclass_with_slots(_cls=None, *, add_dict: bool = False, add_weakref: bool = False, **dataclass_params):
    def wrap(cls):
        cls = dataclass(**dataclass_params)(cls)
        return dataslots(add_dict=add_dict, add_weakref=add_weakref)(cls)

    return wrap if _cls is None else wrap(_cls)
```
but this could be problematic in the future because of conflict of argument names, it blocks adding kwargs to dataslots if needed and there's no help from IDE with arguments to `dataclass`. It's also less intuitive for users imho. 

You can easily add combined decorator to your code. If you don't need any parameters to `dataclass` and `dataslots` you can even add to your code something like:
```
def dataclass_with_slots(cls):
    return dataslots(dataclass(cls))
```
